name: sirius_books
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.1
  freezed_annotation:
  flutter_bloc:
  yx_scope_flutter:
  firebase_auth: 5.4.1
  firebase_core: 3.10.1
  cloud_firestore: 5.6.2

  intl: ^0.19.0
  presentation:
    path: ./presentation

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.3.0
  freezed:
  build_runner:

flutter:
  uses-material-design: true
  generate: true
