name: sirius_books
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  go_router: ^14.8.1
  intl: ^0.19.0
  presentation:
    path: ./presentation
  yx_scope_flutter:

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed:
  surf_lint_rules: ^1.3.0

flutter:
  uses-material-design: true
  generate: true
