name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: Ranot27/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPEN_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" 
          exclude: "**/*.json, **/*.md" 
